### ISSUE TITLE
add tags to docker-compose.yml in the docs so transcoding doesnt fail due to missing libnvcuvid.so.1

### ISSUE THREAD

**Issue by efnats** [HaveAGitGat/Tdarr#1001]
The docker-compose.yml examples in the documentation are missing two settings "privileged and runtime"
Here is a snippet:

```
   devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    privileged: true
    runtime: nvidia
```

Without these settings transcoding often fails with "Failed loading nvcuvid"
See [679](https://github.com/HaveAGitGat/Tdarr/issues/679)
