### ISSUE TITLE
Tdarr server keeps trying to re-register constantly since 2.19.01

### ISSUE THREAD

**Issue by hardwareadictos** [HaveAGitGat/Tdarr#1020]
**Describe the bug**
Tdarr server keeps trying to re-register constantly

**To Reproduce**
Just deploying  2.19.01

**Expected behavior**
Tdarr just being stable without server giving warnings about the re-registering

**Screenshots**
![image](https://github.com/HaveAGitGat/Tdarr/assets/20403906/c16e1350-8065-42e6-9418-ab1c22589105)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]

```
services:
  tdarr:
    privileged: true
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:2.19.01
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/Madrid
      - PUID=0
      - PGID=0
      - UMASK_SET=002
      - serverIP=127.0.0.1
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=tdarr-server1.xxxx.xx
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - auth=true
      - apiKey=XXXXXXXX
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
    volumes:
      - ./server/server:/app/server
      - ./server/configs:/app/configs
      - ./server/logs:/app/logs
      - /mnt/media:/media
      - /mnt/transcodes:/transcodes
      - /mnt/tdarr-cache/:/transcodes/cache
      - /mnt/tdarr-resources:/tdarr-resources
```     

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

Logs are being spammed by this:

```tdarr  | [2024-06-05T10:51:21.980] [ERROR] Tdarr_Node - Node registration error: - nodeID 'ODTiMyk7m' is already taken
tdarr  |      when trying to register nodeName tdarr-server1.xxx.xxx [ID=ODTiMyk7m] [Address=::ffff:127.0.0.1] [PID=270]
tdarr  |      Please restart the Node to generate a new nodeID
tdarr  | [2024-06-05T10:51:30.957] [INFO] Tdarr_Server - Files have not changed since last stats update, no need to update stats again
tdarr  | [2024-06-05T10:51:30.957] [INFO] Tdarr_Server - Delay until next stats update: 10000 ms
tdarr  | [2024-06-05T10:51:31.976] [WARN] Tdarr_Server - Warning: nodeName tdarr-server1.xxx.xxx is being used by multiple Nodes, it's recommended to use a different nodeName for each node.
tdarr  | [2024-06-05T10:51:31.976] [ERROR] Tdarr_Server - Node registration error: - nodeID 'ODTiMyk7m' is already taken
tdarr  |      when trying to register nodeName tdarr-server1.xxx.xxx [ID=ODTiMyk7m] [Address=::ffff:127.0.0.1] [PID=270]
tdarr  |      Please restart the Node to generate a new nodeID
tdarr  | [2024-06-05T10:51:31.978] [ERROR] Tdarr_Node - Node connection error to: 127.0.0.1:8266
tdarr  | [2024-06-05T10:51:31.978] [ERROR] Tdarr_Node - Error
tdarr  |     at Socket.onpacket (/app/Tdarr_Node/node_modules/socket.io-client/build/cjs/socket.js:485:29)
tdarr  |     at Emitter.emit (/app/Tdarr_Node/node_modules/@socket.io/component-emitter/index.js:143:20)
tdarr  |     at /app/Tdarr_Node/node_modules/socket.io-client/build/cjs/manager.js:240:18
tdarr  |     at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
tdarr  |   data: {
tdarr  |     message: "Node registration error: - nodeID 'ODTiMyk7m' is already taken \n" +
tdarr  |       '     when trying to register nodeName tdarr-server1.xxx.xxx [ID=ODTiMyk7m] [Address=::ffff:127.0.0.1] [PID=270]\n' +
tdarr  |       '     Please restart the Node to generate a new nodeID',
tdarr  |     serverVersion: '2.19.01',
tdarr  |     serverError: '',
tdarr  |     autoUpdate: false
tdarr  |   }
tdarr  | }
tdarr  | [2024-06-05T10:51:31.979] [ERROR] Tdarr_Node - Node registration error: - nodeID 'ODTiMyk7m' is already taken
tdarr  |      when trying to register nodeName tdarr-server1.xxx.xxx [ID=ODTiMyk7m] [Address=::ffff:127.0.0.1] [PID=270]
tdarr  |      Please restart the Node to generate a new nodeID
tdarr  | [2024-06-05T10:51:40.957] [INFO] Tdarr_Server - Files have not changed since last stats update, no need to update stats again
tdarr  | [2024-06-05T10:51:40.957] [INFO] Tdarr_Server - Delay until next stats update: 10000 ms
tdarr  | [2024-06-05T10:51:41.978] [WARN] Tdarr_Server - Warning: nodeName tdarr-server1.xxx.xxx is being used by multiple Nodes, it's recommended to use a different nodeName for each node.
```
-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Debian 12 Host with Docker deployiment
 - Browser Firefox - Edge
 - Version 2.19.01

**Additional context**
That tdarr-server1 is not defined on any node, only on the server, on v2.17.01 this wasn't happening.
