### ISSUE TITLE
FFMPEG QSV error on Intel ARC

### ISSUE THREAD

**Issue by slimequeen3251** [HaveAGitGat/Tdarr#1042]
Hello, thank you for adding Intel Arc support! I have a bug though. I can't get it to work with QSV. The VAAPI docker command from here works fine: https://docs.tdarr.io/docs/installation/docker/hardware-transcoding

![image](https://github.com/HaveAGitGat/Tdarr/assets/68612580/c3107ee9-c261-40fe-8f60-df2293d308a8)

Plex is also working fine and transcoding with the GPU.

I ran: 

```
docker run \
    --device=/dev/dri:/dev/dri \
    ghcr.io/haveagitgat/tdarr_node:latest \
    /bin/bash -e \
    -c 'ffmpeg \
            -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
            -c:v:0 hevc_qsv \
            -f null /dev/null'
```

And get: 

```
Stream mapping:
  Stream #0:0 -> #0:0 (wrapped_avframe (native) -> hevc (hevc_qsv))
Press [q] to stop, [?] for help
[hevc_qsv @ 0x55fe6b389080] Selected ratecontrol mode is unsupported
[hevc_qsv @ 0x55fe6b389080] Low power mode is unsupported
[hevc_qsv @ 0x55fe6b389080] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
[vost#0:0/hevc_qsv @ 0x55fe6b388d80] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

FFMPEG Test
![image](https://github.com/HaveAGitGat/Tdarr/assets/68612580/f1865db7-300f-4b41-a33a-4bbfc36fa52f)

I also tried with the plugin: **Boosh-Transcode Using QSV GPU & FFMPEG** and get the same:

![image](https://github.com/HaveAGitGat/Tdarr/assets/68612580/975e7121-7e0c-4cc3-a399-0ef0530c590d)

I've Googled and troubleshooted for hours. Any ideas? Thank you!

Docker compose:

```
version: "3.4"
services:
  tdarr:
    image: haveagitgat/tdarr:2.22.01
    restart: unless-stopped
    container_name: tdarr
    privileged: true
    ports:
      - 8265:8265
      - 8266:8266
    environment:
      - REDACTED_TIMEZONE/REDACTED_TIMEZONE
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=NAS
    volumes:
      - /home/REDACTED/tdarr/server:/app/server
      - /home/REDACTED/tdarr/configs:/app/configs
      - /home/REDACTED/tdarr/logs:/app/logs
      - /mnt/storage/plex/movies:/media/Movies
      - /mnt/storage/plex/tv:/media/TV
      - /tmp/tdarr_cache:/temp
    devices:
      - /dev/dri:/dev/dri

```
