### ISSUE TITLE
Displayed version doesn't change after update

### ISSUE THREAD

**Issue by mariusoei** [HaveAGitGat/Tdarr#1125]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
The version string in the top right corner (and also what tdarr thinks its version is) does not automatically update when I pull the latest image from docker hub.
The documentation does not state any additional steps to update when using docker: [Changing Version](https://docs.tdarr.io/docs/releases/changing-version)

**To Reproduce**
I started tdarr with version 2.24 (the latest version at the time) with the compose file shown below.
Later, I pulled the latest image again using `docker compose pull` and restarted `docker compose up -d`.
The version in the Web UI does not change (still shows 2.24 instead of 2.27). My tdarr_node was also updated to the latest version and the server now shows a version mismatch error when the node tries to connect to the server.

I tried setting up the same container from scratch (simply created a new volume and recreated the container) and it shows the correct version.

**Expected behavior**
When pulling the latest version, I expect the web UI to show the correct version number and also let nodes with that same version connect to it.

**Screenshots**
![grafik](https://github.com/user-attachments/assets/c39b2a56-05a6-42ce-ae3a-8d057086aaaa)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
I use the docker image with this compose file:
```
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - PUID=1001
      - PGID=1002
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=MyInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - tdarr-data:/app
      - /media:/media
```

Server config:
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "auth": false,
  "authSecretKey": "...."
}
```

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[tdarr_server.log](https://github.com/user-attachments/files/18034293/tdarr_server.log)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: Linux (Ubuntu 20.04)
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 2.00.00] 2.27.02

**Additional context**
I'm happy to test anything you like and apologize if this is an error on my part :-)

**Comment by HaveAGitGat** [comment]
The version number in the top right is hardcoded with the release so this means your Docker is either using an old cache version or you mistakenly have an old version running:

You can see the latest images here:

https://github.com/HaveAGitGat/Tdarr/pkgs/container/tdarr

https://hub.docker.com/r/haveagitgat/tdarr/tags

Run `docker image ls --digests` to see the local image digest and compare with here:

https://hub.docker.com/layers/haveagitgat/tdarr/latest/images/sha256-e9d562ede797b9a180e0b398351164b8cff2fe5c4e4c131c13521952dfbb4ea1

![image](https://github.com/user-attachments/assets/69c81499-1a84-4cfa-95d0-561160429dc9)


![image](https://github.com/user-attachments/assets/84050b92-ce7b-4738-8658-97a897fb735b)

Make sure to run `docker compose down` before `docker compose up -d`.

**Comment by mariusoei** [comment]
Thank you for the answer! My local image digest matches the latest image on the Docker Hub.
I found the problem now: I wanted to use a named volume and didn't know how to mount multiple subfolders in there (apparently this functionality was [just added](https://stackoverflow.com/questions/38164939/can-we-mount-sub-directories-of-a-named-volume-in-docker)).
So the volume section of my compose file looked like this:
```
    volumes:
      - tdarr-data:/app
      - /media:/media
      - /media/storage:/media/storage
      - /media/storage/tdarr/transcode_cache:/temp
```
As you can see, the named volume is one level higher than `configs`, `logs` and `server` and thus also includes `Tdarr_Node` and `Tdarr_Server`, which I assume contain the application code itself.

I changed it to the following and it now works just fine:
```
    volumes:
      - type: volume
        source: tdarr-data
        target: /app/server
        volume:
          subpath: server
      - type: volume
        source: tdarr-data
        target: /app/logs
        volume:
          subpath: logs
      - type: volume
        source: tdarr-data
        target: /app/configs
        volume:
          subpath: configs
      - /media/storage:/media/storage
      - /media/storage/tdarr/transcode_cache:/temp
```

I guess I should have just followed the documentation instead of extending the mounted volume contents.
Thank you again for your help and Merry Christmas!
