### ISSUE TITLE
how to properly setup with intel ARC B580?

### ISSUE THREAD

**Issue by picarica** [HaveAGitGat/Tdarr#1184]
**Describe the bug**
so i want to ecnode with with my gpu, i have ARC B580

this is my compose file 

```
# node example
services:
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Bratislava
      - PUID=0
      - PGID=0
      - UMASK_SET=002
      - nodeName=Gentoo-PC-node
      - serverIP=192.168.0.10
      - serverPort=30029
      - inContainer=true
      - ffmpegVersion=7
  
    volumes:
      - ./docker/tdarr/configs:/app/configs
      - ./docker/tdarr/logs:/app/logs
      - ./media:/media
      - ./transcode_cache:/temp
  
    devices:
      - /dev/dri/:/dev/dri

```

only the node, server i have on my NAS with all the files, i have it mounted via sshfs
now do i need tochange my compose file somehow ? or changes my flows too?  i am encoding in AV1 which should work with this card, but it doesnt, its using my CPU, what else i need to setup? i have checked in tdarr webui i clicked  + on the GPU transcode
