### ISSUE TITLE
Setup: Struggling to setup vaapi for h264 | Server (Linux) node and windows node

### ISSUE THREAD

**Issue by Wh1rr** [HaveAGitGat/Tdarr#1185]
# Overall issue
So on both nodes, the vaapi for h264 is enabled. But it is not _working_ (not really sure on the difference there tbh).
## Hardware
- Server is an AMD APU using its iGPU
- Windows PC is my usual gaming rig, AMD CPU with AMD discrete GPU (not always online)

I'll get into software under each heading below.

# Server Node
So this uses docker compose, which I'll add below in a collapsible section.
<details>
<summary>Compose tdarr section</summary>

```yml
tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - nodeName=ServerNode
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
    volumes:
      - ${BASE_PATH}/tdarr/server:/app/server
      - ${BASE_PATH}/tdarr/configs:/app/configs
      - ${BASE_PATH}/tdarr/logs:/app/logs
      - ${MEDIA_SHARE}:/data
      - ${TRANSCODE_PATH:-/transcode_cache}:/temp
    devices:
     - /dev/dri:/dev/dri
    networks:
      - proxy
```

</details>

## Screenshots
![Image](https://github.com/user-attachments/assets/9fff14a2-f713-4963-8d48-1076011ec1ab)
![Image](https://github.com/user-attachments/assets/b85b8c51-8e33-4152-910c-eda59a98b095)

# Windows Node
So, I know this one will be more complex. I've got WSL and virtualization on (I think its needed, but had enabled beforehand). Just using the usual node exe as described in the docs, I also downloaded my own ffmpeg as that didn't have vaapi enabled for any codec. Since downloading, vaapi is enabled for all codecs but only _working_ for hevc.

## Screenshots

![Image](https://github.com/user-attachments/assets/f53fd68e-60e7-48c9-b66e-002f0cbe4bff)
![Image](https://github.com/user-attachments/assets/6da0062a-cfa1-4ff9-a4e2-cecb2434751c)

If this isn't the right place for this, please close and redirect me😃
