### ISSUE TITLE
Websocket always returns 400

### ISSUE THREAD

**Issue by cwpenner** [HaveAGitGat/Tdarr#1189]
**Describe the bug**
The socket.io websocket only ever returns a 400, which causes the webUI to crash and reload every few seconds, making it impossible to use the UI

**To Reproduce**
Deploy in Kubernetes
Navigate to WebUI from secure or insecure route
Watch sockets return 400 (wss: from a secure site, ws: from an insecure site) from the network tab of developer tools in a browser
Watch the UI refresh immediately after socket 400s

**Expected behavior**
I would expect the socket to make a proper connection, and I would love the UI to not constantly refresh as a result.

**Screenshots**
Here's a screenshot of the socket
![Image](https://github.com/user-attachments/assets/67198553-06c9-40be-bc5f-981feed8921e)

Here's the network tab from Chrome showing a bunch of initial 200s, followed by a few 400s that end up causing the UI to refresh
![Image](https://github.com/user-attachments/assets/02c3bc58-2e15-495e-bbcb-aada62a49677)

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.81.208",
  "serverBindIP": false,
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "platform_arch_isdocker": "linux_x64_docker_true",
  "auth": true,
  "authSecretKey": "*****",
  "maxLogSizeMB": 10
}
```

- Job reports: https://docs.tdarr.io/docs/other/job-reports
N/A

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
- [tdarr-59c4978688-7nmxq_tdarr.log](https://github.com/user-attachments/files/19499056/tdarr-59c4978688-7nmxq_tdarr.log)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
N/A

 - OS: Docker (Actually kubernetes)
 - Browser: Chrome and Safari
 - Version: 2.36.01

**Additional context**
I've tried from behind Traefik, using different middleware to try to allow the wss connection, from a cluster IP (not behind Traefik), from Chrome, from Safari, with auth enabled, without auth, etc, all to no avail.

Here's my Kubernetes deployment:

```
apiVersion: v1
kind: Service
metadata:
  name: tdarr
  namespace: media
  labels:
    app: tdarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.81.208
  ports:
    - name: tdarr-http
      port: 80 # Public port
      targetPort: 8265 # Container port
      protocol: TCP
    - name: tdarr-server
      port: 8266 # Public port
      targetPort: 8266 # Container port
      protocol: TCP
  selector:
    app: tdarr

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tdarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tdarr
  template:
    metadata:
      labels:
        app: tdarr
    spec:
      restartPolicy: Always
      volumes:
        - name: data-mount
          persistentVolumeClaim:
            claimName: tdarr-data-claim
        - name: logs-data-mount
          persistentVolumeClaim:
            claimName: tdarr-logs-data-claim
        - name: server-data-mount
          persistentVolumeClaim:
            claimName: tdarr-server-data-claim
        - name: nfs
          persistentVolumeClaim:
            claimName: synology-nfs-claim
      containers:
        - name: tdarr
          image: ghcr.io/haveagitgat/tdarr:latest
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "UTC"
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: UMASK
            value: "002"
          - name: serverIP
            value: "0.0.0.0"
          - name: serverPort
            value: "8266"
          - name: webUIPort
            value: "8265"
          - name: inContainer
            value: "true"
          - name: ffmpegVersion
            value: "7"
          - name: auth
            value: "true"
          - name: authSecretKey
            valueFrom:
              secretKeyRef:
                name: tdarr-auth-key
                key: auth-key
          - name: apiKey
            valueFrom:
              secretKeyRef:
                name: tdarr-api-token
                key: api-token
          ports:
            - name: tdarr-http
              containerPort: 8265
            - name: tdarr-server
              containerPort: 8266
          volumeMounts:
            - name: data-mount
              mountPath: '/app/configs'
            - name: logs-data-mount
              mountPath: '/app/logs'
            - name: server-data-mount
              mountPath: '/app/server'
            - name: nfs
              mountPath: '/movies'
              subPath: 'Plex/Movies'
            - name: nfs
              mountPath: '/tvshows'
              subPath: 'Plex/TV Shows'
            - name: nfs
              mountPath: '/test'
              subPath: 'Plex/test'
            - name: nfs
              mountPath: '/temp'
              subPath: 'TdarrCache'

```

Any help would be greatly appreciated. Thank you!
