### ISSUE TITLE
Schedule does not affect GPU Tasks

### ISSUE THREAD

**Issue by whoiskevinrich** [HaveAGitGat/Tdarr#1198]
The schedule does not affect GPU tasks, only CPU tasks

To reproduce:
1. `docker compose up`
2. Configure library Transcoding for GPU
3. Configure library  schedule to omit the current hour timeframe
4. Review the Tdarr -> Nodes section
5. Notice GPU tasks are still pulled from the queue

Expected Behavior:
- The node should stop processing GPU and CPU tasks for the library.

Configs:
```json
// Tdarr_Server_Config.json
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "serverBindIP": false,
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "auth": false,
  "authSecretKey": "<omitted>",
  "maxLogSizeMB": 10
}

// Tdarr_Node_Config.json
{
  "nodeName": "HostInternalNode",
  "serverURL": "http://0.0.0.0:8266",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "nodeType": "mapped",
  "unmappedNodeCache": "/app/unmappedNodeCache",
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "apiKey": "",
  "maxLogSizeMB": 10,
  "pollInterval": 2000,
  "startPaused": false
}
```
docker-compose.yaml
```
services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=7
      - nodeName=HostInternalNode
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      # omitted, works fine
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

volumes:
  media_volume:
    # omitted, works fine
```
Other context:
Hosted on docker, on Windows 11 using Docker for Desktop
