### ISSUE TITLE
Internal Node stops working when PC Node added

### ISSUE THREAD

**Issue by bwilfong** [HaveAGitGat/Tdarr#1220]
Please put plugin requests/bugs at: https://github.com/HaveAGitGat/Tdarr_Plugins

**Describe the bug**
I run the tdarr server and an internal node, when I run those they run fine. However, when I add a PC-Node, the internal node finished what it was doing and stops working

**To Reproduce**
Start remote node

**Expected behavior**
Both the Internal Node and external node transcode

**Screenshots**
Error on the Internal Node Options - Log
[2025-06-07T22:33:40.641] [INFO] Tdarr_Node - verbose:Launching worker

[2025-06-07T22:33:40.647] [INFO] Tdarr_Node - verbose:Worker easy-eider launched

[2025-06-07T22:33:40.775] [ERROR] Tdarr_Node - Worker easy-eider exited with code 1 and signal null

[2025-06-07T22:33:43.146] [INFO] Tdarr_Node - verbose:Launching worker

[2025-06-07T22:33:43.155] [INFO] Tdarr_Node - verbose:Worker olive-ox launched

[2025-06-07T22:33:43.310] [ERROR] Tdarr_Node - Worker olive-ox exited with code 1 and signal null

[2025-06-07T22:33:44.895] [ERROR] Tdarr_Node - Worker corny-crab disconnected. Pruning.

[2025-06-07T22:33:44.896] [ERROR] Tdarr_Node - Worker light-lamb disconnected. Pruning.

[2025-06-07T22:33:44.896] [ERROR] Tdarr_Node - Worker fuzzy-fugu disconnected. Pruning.

[2025-06-07T22:33:44.897] [ERROR] Tdarr_Node - Worker total-toad disconnected. Pruning.

[2025-06-07T22:33:45.844] [INFO] Tdarr_Node - verbose:Launching worker

[2025-06-07T22:33:45.851] [INFO] Tdarr_Node - verbose:Worker key-kudu launched

[2025-06-07T22:33:45.983] [ERROR] Tdarr_Node - Worker key-kudu exited with code 1 and signal null

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
Tdarr_Server_Congfig.json
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "192.168.1.129",
  "serverBindIP": false,
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": "",
  "auth": false,
  "authSecretKey": "tsec_Ptt1EkvQqNJJX_pzyjVl9NIWqiCBj",
  "maxLogSizeMB": 10,
  "bypassAuthOnLocalhost": false
}

Tdarr_Node_Config.json
{
  "nodeID": "ZimaNode",
  "nodeName": "ZimaNode",
  "serverURL": "http://192.168.1.129:8266",
  "serverIP": "192.168.1.129",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "nodeType": "mapped",
  "unmappedNodeCache": "/app/unmappedNodeCache",
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": "",
  "apiKey": "",
  "maxLogSizeMB": 10,
  "pollInterval": 2000,
  "startPaused": false
}

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]

 - OS: CasaOS, tdarr is running in a portainer container
 - Browser Chrome
 - Version 2.42.01

**Additional context**
Docker Compose

```
version: "3.9"
services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
#    runtime: nvidia
#    container_name: Tdarr
    hostname: tdarr
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8265/ || exit 1
    ports:
      - 8265:8265
      - 8266:8266
      - 8267:8267 # Internal node port
#      - 8268:8268 # Example extra node port
    environment:
      - TZ=America/Los_Angeles
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=tdarr
      - serverIP=192.168.1.129
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=ZimaNode
#     - inContainer=true
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /DATA/AppData/tdarr/server:/app/server
      - /DATA/AppData/tdarr/configs:/app/configs
      - /DATA/AppData/tdarr/logs:/app/logs
      - /mnt/plexmedia:/media
      - /mnt/plexmedia/transcode:/temp
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
```
