### ISSUE TITLE
Docker installation problem" "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?"

### ISSUE THREAD

**Issue by tehniemer** [HaveAGitGat/Tdarr#223]
**Describe the bug**
tdarr will not start after docker install

**To Reproduce**
Install using docker-compose either with a volume or mapped host folder for the DB
```
  tdarr:
    image: haveagitgat/tdarr
    container_name: tdarr
    restart: always
    networks:
      - proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$TDARR_PORT:8265"
    volumes:
      - $CONFIG_DIR/tdarr:/home/Tdarr/Documents/Tdarr
      - tdarrDB:/var/lib/mongodb
      - $MEDIA_DIR:/home/Tdarr/media
      - $DOWN_DIR/tdarr:/home/Tdarr/cache
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
```

**Expected behavior**
tdarr installs and initializes 

**Observed behavior**
docker logs are filled with the following error
```sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?```
