### ISSUE TITLE
Container fails to start.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#226]
**Describe the bug**
Tdarr docker container fails to start. 

**To Reproduce**
Container was installed using the following docker-compose.yaml:
```
tdarr_aio:
    image: haveagitgat/tdarr
    container_name: tdarr
    ports:
      -  8265:8265
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/user/Tdarr:/home/Tdarr/Documents/Tdarr
      - /mnt/media/video:/home/Tdarr/media
      - /mnt/media/transcode:/home/Tdarr/cache
      - /mnt/hdd/mongo:/var/lib/mongodb
    devices:
      - /dev/dri:/dev/dri
```

**Expected behavior**
Container should start and tdarr web interface becomes available.

**Screenshots**
The only log output for the container is:
```   
 * Starting database mongodb
   ...fail!
```

**System:**
 - OS: Ubuntu 20.04 Focal on x86_64
 - Docker version: 19.03.8, build afacb8b7f0

This error occurred on the all in on containers prior to them being merged. The only way I was able to start tdarr was using the seperate containers for it and mongodb.
