### ISSUE TITLE
Problems accessing the database

### ISSUE THREAD

**Issue by Demon-tk** [HaveAGitGat/Tdarr#315]
**Describe the bug**
I received this warning upon boot of Tdarr in docker: 
`[2021-01-15T18:54:31.854] [WARN] Tdarr_Server - Database has not finished initialising, waiting. Status is shown in UI. `

_P.S. "initialising" is spelled wrong_

[Screenshot](https://cdn.discordapp.com/attachments/623799920574595092/799788459673649172/unknown.png)

**To Reproduce**
Unknown, using Docker on Ubuntu Server image v. Beta 1.99.11

**Expected behavior**
The database should init properly and be read so that Tdarr can perform operations

**Screenshots**
File permissions within Docker container:
```txt
nate@mendeshomeserver:~/docker/tdarr/data$ sudo docker container exec tdarr ls -la
total 84
drwxr-xr-x   1 root  root  4096 Jan 15 17:22 .
drwxr-xr-x   1 root  root  4096 Jan 15 17:22 ..
-rwxr-xr-x   1 root  root     0 Jan 15 17:21 .dockerenv
drwxr-xr-x   1 Tdarr Tdarr 4096 Jan 15 17:21 app
lrwxrwxrwx   1 root  root     7 Jul 20 10:43 bin -> usr/bin
drwxr-xr-x   2 root  root  4096 Apr 15  2020 boot
drwxr-xr-x   6 root  root   360 Jan 15 19:02 dev
drwxr-xr-x   1 root  root  4096 Jan 15 19:02 etc
-rw-r--r--   1 root  root     0 Jan 15 17:22 firstRun
drwxr-xr-x   1 root  root  4096 Dec 21 11:48 home
-rwxr-xr-x   1 root  root   389 May 13  2020 init
lrwxrwxrwx   1 root  root     7 Jul 20 10:43 lib -> usr/lib
lrwxrwxrwx   1 root  root     9 Jul 20 10:43 lib32 -> usr/lib32
lrwxrwxrwx   1 root  root     9 Jul 20 10:43 lib64 -> usr/lib64
drwxr-xr-x   2 root  root  4096 May 12  2020 libexec
lrwxrwxrwx   1 root  root    10 Jul 20 10:43 libx32 -> usr/libx32
drwxr-xr-x   1 Tdarr Tdarr 4096 Dec 21 11:48 logs
drwxr-xr-x   2 Tdarr Tdarr    0 Jan 11 14:56 media
drwxr-xr-x   2 root  root  4096 Jul 20 10:43 mnt
drwxr-xr-x   2 root  root  4096 Jul 20 10:43 opt
dr-xr-xr-x 252 root  root     0 Jan 15 19:02 proc
drwx------   2 root  root  4096 Jul 20 10:57 root
drwxr-xr-x   1 root  root  4096 Jan 15 17:21 run
lrwxrwxrwx   1 root  root     8 Jul 20 10:43 sbin -> usr/sbin
drwxr-xr-x   2 root  root  4096 Jul 20 10:43 srv
dr-xr-xr-x  13 root  root     0 Jan 15 18:36 sys
drwxr-xr-x   3 Tdarr Tdarr 4096 Jan 15 14:56 temp
drwxrwxrwt   1 root  root  4096 Jan 15 19:02 tmp
drwxr-xr-x   1 root  root  4096 Aug  1 21:32 usr
drwxr-xr-x   1 root  root  4096 Jul 20 10:57 var
```

File permissions within Ubuntu server:
```
nate@mendeshomeserver:~/docker/tdarr/data$ sudo ls -la ~/docker/tdarr
total 36
drwxr-xr-x  7 root root 4096 Jan 15 23:16 .
drwxr-xr-x 11 root root 4096 Jan 14 22:05 ..
drwxr-xr-x  3 nate nate 4096 Jan 15 19:56 cache
drwxr-xr-x  9 nate nate 4096 Jan 16 00:02 config
drwxr-xr-x  3 nate nate 4096 Jan 15 22:22 data
drwxr-xr-x  4 nate nate 4096 Jan 15 21:59 db
-rw-r--r--  1 root root 1212 Jan 15 22:35 docker-compose.yml
-rw-r--r--  1 root root  612 Jan 15 23:16 docker-compose.yml.save
drwxr-xr-x  2 nate nate 4096 Jan 15 22:37 logs
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Server
 - Browser Chromium variant
 - Version 3.6.2160.3 (Official Build) (64-bit)

**Additional context**
My `docker-compose.yml`
```yml
version: "3"
services:
  tdarr:
    container_name: tdarr
    devices:
      - CgroupPermissions: rwm
        PathInContainer: /dev/dri
        PathOnHost: /dev/dri
    entrypoint:
      - /init
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
      - serverPort=8266
      - webUIPort=8265
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - UMASK=002
      - HOME=/home/Tdarr
      - PORT1=8265
      - PORT2=8266
      - ROOT_URL=http://localhost
      - LANGUAGE=en_US.UTF-8
      - LANG=
      - LC_ALL=
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - DEBIAN_FRONTEND=noninteractive
      - LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri/
      - LD_LIBRARY_PATH=/usr/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
      - S6_REL=2.0.0.1
      - NODE_VERSION=14
      - WEB_UI_PORT=8265
      - SERVER_PORT=8266
    hostname: mendeshomeserver
    image: haveagitgat/tdarr:1.99.11
    ipc: private
    labels:
      com.docker.compose.config-hash: bc76ec8a9d1dd33eb30f2fc1d4c3eb7acfcfff3b929e3b618bc778330455b552
      com.docker.compose.container-number: 1
      com.docker.compose.oneoff: False
      com.docker.compose.project: tdarr
      com.docker.compose.project.config_files: docker-compose.yml
      com.docker.compose.project.working_dir: /home/nate/docker/tdarr
      com.docker.compose.service: tdarr
      com.docker.compose.version: 1.27.4
    logging:
      driver: json-file
      options: {}
    networks:
      host:
        aliases:
    ports:
      - 8265:8265/tcp
      - 8266:8266/tcp
    restart: unless-stopped
    volumes:
      - /home/nate/docker/tdarr/config:/app/configs:rw
      - /home/nate/docker/tdarr/data:/app/server:rw
      - /media/data/library:/media:rw
      - /home/nate/docker/tdarr/cache:/temp:rw
      - /home/nate/docker/tdarr/logs:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
networks:
  host:
    external: true
```
