### ISSUE TITLE
V2.00.06 web UI will not start in docker container.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#376]
**Describe the bug**
Web UI is not available after container start up.

**To Reproduce**
Start tdarr containers.
Attempt to connect to webUI

**Expected behavior**
Web UI should be available.

**Please provide the following information:**
Docker compose log: https://pastebin.com/wzNWLY6s

Docker compose file:
```
version: '2'
services:
  tdarr:
    container_name: tdarr_new
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - serverIP=192.168.0.68
      - serverPort=8266
      - webUIPort=8265
    image: 'haveagitgat/tdarr:2.00.06'
    ports:
      - '8265:8265'
      - '8266:8266'
    restart: unless-stopped
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/home/user/Tdarr:/app/server'
      - '/mnt/media/video:/mount'
      - '/mnt/process/transcode/tdarr:/home/Tdarr/cache'
    network_mode: host
  tdarr_node:
    container_name: tdarr_new_node
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
      - serverIP=192.168.0.68
      - serverPort=8266
      - nodeID=odyssey
    image: 'haveagitgat/tdarr_node:2.00.06'
    ports:
      - '8267:8267'
    restart: unless-stopped
    volumes:
      - '/mnt/media/video:/mount'
      - '/mnt/process/transcode/tdarr:/home/Tdarr/cache'
    devices:
      - /dev/dri:/dev/dri
    mem_limit: 5G
    network_mode: host
```

Tdarr_WebUI_Config.json from /app/config in the container:
```
{
  "webUIPort": "8265",
  "serverIP": "192.168.0.68",
  "serverPort": "8266"
}
```

Tdarr_Server_Config.json from /app/config in the container:
```
{
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": ""
}
```

**Additional context**
No configuration changes were made when updating to .06. Just did ``docker-compose pull`` to update and then restarted.
