### ISSUE TITLE
New setup with tdarr_aio not saving settings

### ISSUE THREAD

**Issue by goku-son** [HaveAGitGat/Tdarr#427]
Tdarr Beta 1.3003

For some reason, my settings are not being saved and all but one of the directories has files in it after starting container. My image is image: haveagitgat/tdarr_aio. Here are my volumes config:

volumes:
      - ./cache:/temp
      - ./appdata:/app/server
      - ./appdata:/app/configs
      - ./appdata:/app/logs
      - ./home/Tdarr/Documents/Tdarr:/home/Tdarr/Documents/Tdarr
      - /share/CACHEDEV1_DATA/Multimedia:/media
 
 I can get to the GUI, and even setup my library and start a transcode, but when I restart everything gets reset. There are some files and directories in /home/Tdarr/Documents/Tdarr/ but not in any of the other volumes above. 
 
I am pretty sure I am doing something wrong but not sure exactly what. Any pointers would be appreciated. Thanks in advance!

**Comment by goku-son** [comment]
Here is my compose file in case it helps:
`networks:
  mylan:
    external: true
    name: mylan
services:
  tdarr:
    container_name: tdarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/Chicago
    image: haveagitgat/tdarr_aio
    networks:
      mylan:
        ipv4_address: 10.0.100.99
    restart: unless-stopped
    volumes:
    - /share/CACHEDEV2_DATA/Containers/tdarr/cache:/temp:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/appdata:/app/server:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/appdata:/app/configs:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/appdata:/app/logs:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/home/Tdarr/Documents/Tdarr:/home/Tdarr/Documents/Tdarr:rw
    - /share/CACHEDEV1_DATA/Multimedia:/media:rw
version: '2.1' `

**Comment by goku-son** [comment]
Here is my complete compose file:

```
networks:
  mylan:
    external: true
    name: mylan
services:
  tdarr:
    container_name: tdarr
    environment:
      PGID: '1000'
      PUID: '1000'
      TZ: America/Chicago
    image: haveagitgat/tdarr_aio
    networks:
      mylan:
        ipv4_address: 10.0.100.99
    restart: unless-stopped
    volumes:
    - /share/CACHEDEV2_DATA/Containers/tdarr/cache:/temp:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/appdata:/app/server:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/appdata:/app/configs:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/appdata:/app/logs:rw
    - /share/CACHEDEV2_DATA/Containers/tdarr/home/Tdarr/Documents/Tdarr:/home/Tdarr/Documents/Tdarr:rw
    - /share/CACHEDEV1_DATA/Multimedia:/media:rw
version: '2.1'
```
