### ISSUE TITLE
Install cuda on docker tdarr-node

### ISSUE THREAD

**Issue by daviddavo** [HaveAGitGat/Tdarr#479]
**Describe the bug**
Cuda GPU workers don't work inside docker

**To Reproduce**
Use a docker worker with cuda

**Expected behavior**
The transcoding to work

-Worker error
```
[h264_cuvid @ 0x55fb0eddca80] Cannot load libnvcuvid.so.1
[h264_cuvid @ 0x55fb0eddca80] Failed loading nvcuvid.
```

**Comment by modem7** [comment]
Yes they do. 

You need to pass it through to the container. 

Here's an exerpt of mine.

```yaml
  tdarr-node:
    container_name: Tdarr-node
    image: haveagitgat/tdarr_node:latest
    hostname: TdarrNode
    restart: always
    networks:
      isonet:
        ipv4_address: $TDARRNODEIP
    environment:
      - TZ=Europe/London
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - nodeID=MainNode
      - nodeIP=$TDARRNODEIP
      - nodePort=8267
      - serverIP=$TDARRSERVERIP
      - serverPort=8266
    runtime: nvidia
    devices:                                                                                               
      - /dev/dri:/dev/dri
    volumes:
      - $USERDIR/TdarrServer/Configs:/app/configs
      - $USERDIR/TdarrServer/Logs:/app/logs
      - $RAMDRIVE:/home/Tdarr/Cache
    depends_on:
      - tdarr
```
