### ISSUE TITLE
WebUI reports less memory usage than docker reports

### ISSUE THREAD

**Issue by bergi9** [HaveAGitGat/Tdarr#681]
**Describe the bug**
The WebUI reports less memory usage than docker reports.

**To Reproduce**
Start tdarr in docker and compare the reported memory usage between webui and docker

**Expected behavior**
The WebUI should report almost same memory usage as docker reports.

**Screenshots**
![WebUI](https://user-images.githubusercontent.com/5556750/189302194-db98b0c7-a69d-4d0e-a111-15448e7b4c3c.png)
![Docker](https://user-images.githubusercontent.com/5556750/189302221-a9dbe81e-60a3-41f4-a5f6-2e9670ba3a20.png)

**Please provide the following information:**
 - OS: Unraid/Linux
 - Browser: any
 - Version: 2.00.18

**docker-compose.yaml**
```yaml
version: '3'

services:
  master:
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    runtime: nvidia
    #ports:
      #- "8265:8265" # WebUI Port
      #- "8266:8266" # Server Port
      #- "8267:8267" # internal Node Port
      #- "8268:8268" # extra node port
    volumes:
      - /mnt/cache/appdata/tdarr/server:/app/server
      - /mnt/cache/appdata/tdarr/configs:/app/configs
      - /mnt/cache/appdata/tdarr/logs:/app/logs
      - /mnt/cache/tdarr/media/:/mnt/media
      - /mnt/cache/tdarr/cache/:/temp
    environment:
      TZ: Europe/Berlin
      PUID: 99
      PGID: 100
      webUIPort: 8265
      serverIP: 0.0.0.0
      serverPort: 8266
      internalNode: true
      nodeID: MyInternalNode
      #nodeIP: 0.0.0.0
      #nodePort: 8267
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    networks:
      - traefik-net
      #- tdarr-net
    labels:
      net.unraid.docker.icon: "/boot/config/icons/tdarr.png"
      traefik.enable: true
      traefik.http.routers.tdarr.rule: Host(`tdarr.server.local`)
      traefik.http.routers.tdarr.entrypoints: web
      traefik.http.routers.tdarr.service: tdarr
      traefik.http.services.tdarr.loadbalancer.server.scheme: http
      traefik.http.services.tdarr.loadbalancer.server.port: 8265
```
