### ISSUE TITLE
Could this application be extended to use ffmpeg as a general workflow orchestrator rather than just transcoding with ffmpeg?

### ISSUE THREAD

**Issue by aqueeb** [HaveAGitGat/Tdarr#740]
**Is your feature request related to a problem? Please describe.**
I use ffmpeg in my video editing and it frustrates me to run multiple ffmpeg commands to:
- Trim the files. This process involves me figuring out time stamps and then using ffmpeg to cut the parts that I want from the source footage using multiple runs of ffmpeg over the source with different sets of timestamps for each section that I want from the source material.
- Join the files into one.

**Describe the solution you'd like**
I pass the pair (start and finish) of timestamps and everything is taken care of by an application

**Describe alternatives you've considered**
Apache Airflow and Temporal ([temporal.io](https://temporal.io/)) are two. Since both of them have a learning curve, I'm sorely tempted to pick one and learn it but at the same time, I can create a simple data model, yaml it out and feed it to a python script that orchestrates ffmpeg to do what's in the yaml file.

**Additional context**
Something like the following:
```
stage
 - 1:
    cut:
        - srcFileName: GX001002.MP4
          cutIn: 00:12
          cutOut: 00:15
          outFileName: GX001002-00-12--00-15.MP4
        - srcFileName: GX001002.MP4
          cutIn: 01:12
          cutOut: 02:15
          outFileName: GX001002-01-12--02-15.MP4
        - srcFileName: GX001002.MP4
          cutIn: 03:12
          cutOut: 04:15
          outFileName: GX001002-03-12--04-15.MP4
    someFfmpegCmdLineArg:
        - aListOfFileNameOverWhichToPerformThisCmdLineArg
        - aListOfFileNameOverWhichToPerformThisCmdLineArg
        - aListOfFileNameOverWhichToPerformThisCmdLineArg
        - aListOfFileNameOverWhichToPerformThisCmdLineArg
- 2:
    AnotherSetofsomeFfmpegCmdLineArgs:

```
I just hacked it together to provide an idea but this is the kind of simple data model I was talking about. Hope this helps!
