### ISSUE TITLE
Kubernetes deployments

### ISSUE THREAD

**Issue by agilob** [HaveAGitGat/Tdarr#750]
Not sure if many people will be looking for it, I did and couldn't find it so wrote the below deployment files:

As you will see below:
* `media` is namespace so it's used in server domain
* shares are accessed from NFS from `nfs.lan` hostname

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: tdarr
spec:
  selector:
    matchLabels:
      app: tdarr
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tdarr
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: nfs
    spec:
      volumes:
        - name: tdarr-server
          hostPath:
            path: /mnt/tdarr/server
            type: Directory
        - name: tdarr-config
          hostPath:
            path: /mnt/tdarr/config
            type: Directory
        - name: media
          hostPath:
            path: /host-media
            type: Directory
        - name: cache
          hostPath:
            path: /mnt/tdarr/cache
            type: Directory
      containers:
        - name: tdarr
          image: ghcr.io/haveagitgat/tdarr
          volumeMounts:
            - name: cache
              mountPath: /temp
            - name: media
              mountPath: /media
            - name: tdarr-config
              mountPath: /app/configs
            - name: tdarr-server
              mountPath: /app/server
          ports:
            - containerPort: 8266
            - containerPort: 8265
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: nodeName
              value: "server-node"
            - name: internalNode
              value: "true"
            - name: webUIPort
              value: "8265"
            - name: serverPort
              value: "8266"
            - name: serverIP
              value: "0.0.0.0"
          resources:
            limits:
              cpu: "10"
              memory: "6Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
          securityContext:
            privileged: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  namespace: media
  name: tdarr
spec:
  type: ClusterIP
  selector:
    app: tdarr
  ports:
    - port: 8265
      targetPort: 8265
---
apiVersion: v1
kind: Service
metadata:
  namespace: media
  name: tdarr-server
spec:
  type: ClusterIP
  selector:
    app: tdarr
  ports:
    - port: 8266
      targetPort: 8266
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: tdarr-node
spec:
  selector:
    matchLabels:
      app: tdarr-node
  revisionHistoryLimit: 10
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tdarr-node
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: hpbook
      volumes:
        - name: tdarr-config
          hostPath:
            path: /home/agilob/dockers/tdarr/config
            type: Directory
        - name: cache
          hostPath:
            path: /home/agilob/dockers/tdarr/cache
            type: Directory
        - name: disk
          nfs:
            server: nfs.lan
            path: /host-media
      containers:
        - name: tdarr
          image: ghcr.io/haveagitgat/tdarr_node
          volumeMounts:
            - name: tdarr-config
              mountPath: /app/configs
            - name: disk
              mountPath: /media
            - name: cache
              mountPath: /temp
          ports:
            - containerPort: 8266
          env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: nodeName
              value: "NODE_NAME"
            - name: serverPort
              value: "8266"
            - name: serverIP
              value: "tdarr-server.media"
          resources:
            limits:
              cpu: "10"
              memory: "6Gi"
            requests:
              cpu: "2"
              memory: "2Gi"
          securityContext:
            privileged: true
            capabilities:
              drop: ["ALL"]
```
