### ISSUE TITLE
Docker CPU usage limited to one thread per encode in unRAID

### ISSUE THREAD

**Issue by DesertCookie** [HaveAGitGat/Tdarr#777]
**Describe the bug**
I've noticed Tdarr in Docker, specifically unRAID, only using a single thread per encode.

**To Reproduce**
Install `haveagitgat/tdarr` from DockerHub using unRAID's community applications.

**Expected behavior**
An encode should scale across all available threads just as is happening with Windows nodes.

 - OS: unRAID 6.11.5 with Docker 20.10.21
 - Browser: Firefox
 - Version: 2.00.20

**Comment by HaveAGitGat** [comment]
Hi do you have the job report for when you run a transcode? https://docs.tdarr.io/docs/other/job-reports/

Just in case you're using commands which are limiting it.

**Comment by DesertCookie** [comment]
Here's a job report for you: [Lglq0qSi9H-log.txt](https://github.com/HaveAGitGat/Tdarr/files/11485751/Lglq0qSi9H-log.txt)

It has no issues scaling across 6-8 threads per encode on my Windows machine, so it's not an issue with the VP9 encode command. If needed I could narrow it down to being a Docker (or Docker in unRAID) issue by converting my two Windows nodes to Docker in Windows nodes temporarily and see if the same issues appear.

**Comment by HaveAGitGat** [comment]
Everything is fine with the command being run so seems like an issue with the operating system scheduler or something like that.

Some info here: https://forums.unraid.net/topic/103178-how-does-cpu-pinningisolation-work/

So maybe can try isolation and see if you still have the same issue.

**Comment by DesertCookie** [comment]
I have Tdarr pinned to four threads. All of those are isolated. Next time I restart I'll try putting them on non-isolated threads and see if it scales beyond two threads then.

**Comment by Istria1704** [comment]
I have the same or similar issue. I installed tdar yesterday using docker compose. 

And whether I set "Transcode CPU" to 1, 2, 4 or even 10. When a transcode starts, it only uses 1 worker. And the cpu load of the container (which has 2 cores allocated to it) is stable around 40-50%.
Could it be audio transcode (AC35.1 to AAC2.0 in this testcase) are always single-threaded? I have not tried a video transcode yet.

**Setup**
OS: Proxmox with Debian 12 in a LXC container. Docker installed on said Debian container.
CPU: AMD GX-420GI (2 cores allocated to the tdarr container)
RAM: 8GB (2GB allocated to the tdarr container)

**Docker** Compose file:
```
---
version: "3"
services:
#########################################
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port
      - 8268:8268 # Example extra node port
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1001
      - PGID=100
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - nodeID=MyInternalNode
    volumes:
      - /opt/tdarr/server:/app/server
      - /opt/tdarr/config:/app/configs
      - /opt/tdarr/logs:/app/logs
      #- /mnt/MoviesSeriesOMV1:/MoviesSeriesOMV1
      #- /mnt/MoviesSeriesOMV2:/MoviesSeriesOMV2
      - /mnt/MoviesSeriesOMV3/tdarr:/OMV3tdarr
```
**Screenshots with active transcode**
![image](https://github.com/HaveAGitGat/Tdarr/assets/39712196/f8a6b0af-03dc-4c70-a58f-2f3ae25fe77d)

![image](https://github.com/HaveAGitGat/Tdarr/assets/39712196/beebf572-01cd-48ae-a2c2-5ecbf3733dbd)
