### ISSUE TITLE
Node name not respecting variable

### ISSUE THREAD

**Issue by modem7** [HaveAGitGat/Tdarr#912]
**Describe the bug**
Node name not respecting variable

**To Reproduce**
`nodeName=Mynode`

**Expected behavior**
For node to respect name change when setting variable. 

![image](https://github.com/HaveAGitGat/Tdarr/assets/4349962/0aaedc41-cd7c-42e2-8e57-ac5f258280d2)

**Please provide the following information:**
[tdarr.zip](https://github.com/HaveAGitGat/Tdarr/files/13395652/tdarr.zip)

 - OS: Ubuntu Docker
 - Version 2.15.01

**Additional context**
Compose:
```yaml
#  Tdarr - Media transcoding
  tdarr:
    container_name: Tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: always
    hostname: Tdarr
    networks:
      pihole:
        ipv4_address: '172.22.0.141'
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port.
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UMASK_SET=002
      # - serverIP=0.0.0.0
      # - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=HDA
    labels:
      - backup
      - autoheal=true
      ## Homepage
      - homepage.name=Tdarr
      - homepage.group=Media Management
      - homepage.icon=tdarr
      - homepage.href=http://hda:8265
      - homepage.widget.type=tdarr
      - homepage.widget.url=http://tdarr:8265
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - $USERDIR/TdarrServer/Server:/app/server
      - $USERDIR/TdarrServer/Configs:/app/configs
      - $USERDIR/TdarrServer/Logs:/app/logs
      - $TRANSCODEDIR:/temp
      - $MEDIA:/Media
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
```

```json
{
"nodeID":"hPQlyzgnL"
"nodeName":"InternalNode"
"serverIP":"0.0.0.0"
"serverPort":"8266"
"handbrakePath":""
"ffmpegPath":""
"mkvpropeditPath":""
"pathTranslators":[
0:{
"server":""
"node":""
}
]
"logLevel":"INFO"
"priority":-1
"platform_arch_isdocker":"linux_x64_docker_true"
"processPid":236
"cronPluginUpdate":""
"nodeIP":"0.0.0.0"
"nodePort":"8267"
"platform_arch":"linux_x64_docker_true"
"uptime":255
}
```

**Comment by HaveAGitGat** [comment]
Have you tried recreating the container or launching from a new terminal in case you or something else set the nodeName env variable? Would be an odd one for this not to be working, I’m sure I’d have many messages about it

**Comment by modem7** [comment]
> Have you tried recreating the container or launching from a new terminal in case you or something else set the nodeName env variable? Would be an odd one for this not to be working, I’m sure I’d have many messages about it 

Heya,

That I have! It seems to work when initially setting up the container for the first time, but not in subsequent changes.

Could I confirm the variable is `nodeName` with that capitalisation? 

Agreed that it's definitely an odd one!

**Comment by modem7** [comment]
OK, I've just tested this on my second node and I'm not seeing the same behaviour. 

Second node yaml: 
```yaml
 ##############
 ##Tdarr Node##
 ##############
 
  tdarr-node:
    container_name: Tdarr-Node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    network_mode: host
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - UMASK_SET=002
      - nodeName=Frodo
      - serverIP=192.168.50.254
      - serverPort=8266
      - inContainer=true
    volumes:
      - $USERDIR/Tdarr/configs:/app/configs
      - $USERDIR/Tdarr/logs:/app/logs
      - /mnt/media:/Media
      - /mnt/transcode:/temp
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always
```

**Comment by HaveAGitGat** [comment]
Yes `nodeName` is correct. The node in the server image and the node in the node image use the exact same code so if it's working in one then should be working in other. I've tried using the same node names as you and have not been able to recreate this issue. 

I have not heard about this issue from anyone else so seems like it's something with your local setup causing the env variable to stick.

To be clear, new env vars aren't applied if you simply restart the container. You'd need to do the following for changes to take effect:

`docker-compose down`
`docker-compose up`

I can look into this further if there are clear steps to recreate this on any machine, thanks. If anyone else has this issue then feel free to add to it.

**Comment by modem7** [comment]
Heya, 

Not quite sure how much more I can provide bar the above. 

I do compose up/down as standard to apply any modifications to containers. 

As above, my config is as follows:

```yaml
#  Tdarr - Media transcoding
  tdarr:
    container_name: Tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: always
    hostname: Tdarr
    networks:
      pihole:
        ipv4_address: '172.22.0.141'
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
      - 8267:8267 # Internal node port.
    environment:
      - TZ=$TZ
      - PUID=$PUID
      - PGID=$PGID
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - UMASK_SET=002
      # - serverIP=0.0.0.0
      # - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - nodeName=Node1
    labels:
      - backup
      - autoheal=true
      ## Homepage
      - homepage.name=Tdarr
      - homepage.group=Media Management
      - homepage.icon=tdarr
      - homepage.href=http://hda:8265
      - homepage.widget.type=tdarr
      - homepage.widget.url=http://tdarr:8265
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - $USERDIR/TdarrServer/Server:/app/server
      - $USERDIR/TdarrServer/Configs:/app/configs
      - $USERDIR/TdarrServer/Logs:/app/logs
      - $TRANSCODEDIR:/temp
      - $MEDIA:/Media
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
```

Changing nodename does not change the node's name in this particular case. 

https://github.com/HaveAGitGat/Tdarr/assets/4349962/f379b0dd-59d4-4b4e-8d60-e52cda802d7d
