### ISSUE TITLE
cant transcode files containing  accents

### ISSUE THREAD

**Issue by yodog** [HaveAGitGat/Tdarr#968]
tdarr is unable to transcode files with accents in their names, it doesnt matter how many times i try.

if manually rename the files, removing the accents, it works.

transcode error tab:

```
1 series 2024-02-19 15:58:59 Westworld - S04E08 - Que Será Será WEBDL-1080p.mp4
2 series 2024-02-19 15:58:55 Westworld - S04E03 - Années Folles WEBDL-1080p.mp4
3 series 2024-02-19 15:58:06 Westworld - S02E03 - Virtù e Fortuna HDTV-1080p.mp4
4 series 2024-02-19 15:57:33 Westworld - S02E07 - Les Écorchés HDTV-1080p.mp4
```

**before renaming (error)**

```
2024-02-19T15:59:01.340Z 6CmgtcIFNy:Node[yearly-yak]:Worker[key-kid]:[1/2] R/W [-error-]:/media/series/Westworld/Westworld - S04E08 - Que Será Será WEBDL-1080p.mp4:Error: ENOENT: no such file or directory, access '/media/series/Westworld/Westworld - S04E08 - Que Será Será WEBDL-1080p.mp4'

2024-02-19T15:59:01.340Z 6CmgtcIFNy:Node[yearly-yak]:Worker[key-kid]:[2/2] The  following source file cannot be accessed on Tdarr_Node 0OA9VTV6m: "/media/series/Westworld/Westworld - S04E08 - Que Será Será WEBDL-1080p.mp4"
```

**after renaming (success)**

```
2024-02-19T17:54:01.808Z N72A1KK6C:Attempting copy from /tmp/Westworld - S04E08 - Que Sera Sera WEBDL-1080p-TdarrCacheFile-Yxmwr35EC.mp4 to /media/series/Westworld/Westworld - S04E08 - Que Sera Sera WEBDL-1080p-TdarrCacheFile-7PeMTWJolM.mp4 , method 1

2024-02-19T17:54:01.809Z N72A1KK6C:After move/copy,  destination file of size 1001712011 does match cache file of size 1001712011
```

**Comment by wnypoker** [comment]
I had the same issue with accents in file names, the files were located on a SMB mount.

**Comment by Hisui02** [comment]
Same here I had to manually rename them to the Tdarr expected name to make it move them, sadly later Sonarr has to rename the file again

**Comment by HaveAGitGat** [comment]
I have also tried this using a Linux SMB share accessed from a Windows Tdarr server and node and it completed successfully with flows and plugin stack so doesn't seem that is the cause.

Haven't had any more people encountering this so feel free to add any details here about recreating the issue if it comes up, thanks.

**Comment by yodog** [comment]
> Do you have any more info on your environment? I have tried with that exact file name using plugin stack and flows and it has come out as successful for me:
> 

maybe. i will start showing my docker compose files. if you need anything else, ill be glad to provide.

### linux:

```
x-env: 
  environment: &env
    NODEHOSTIP: ${HOSTIP}
    NODEHOSTNAME: '{{.Node.Hostname}}'
    PGID: 1000
    PUID: 1000
    TZ: America/Sao_Paulo

x-hosts: 
  extra_hosts: &hosts
    - "host.docker.internal:host-gateway"
    - "host.docker.internal:${HOSTIP}"

networks:
  intercontainers:
    external: true

services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr
    networks: [ intercontainers ]
    ports: [ 8265:8265, 8266:8266 ]
    extra_hosts: *hosts
    environment:
      <<:  *env
      ffmpegVersion: '6'
      inContainer: 'true'
      internalNode: 'true'
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - /data/media:/media
      - /data/transcode:/tmp
      - /docker-volumes/tdarr:/app/configs
      - /docker-volumes/tdarr:/app/logs
      - /docker-volumes/tdarr:/app/server
```

### windows node:

```
volumes:
  tdarr:
  media:
    driver_opts:
      type: cifs
      o: username=xxx,password=xxx,uid=1000,gid=1000
      device: //192.168.100.39/data/media
  transcode:
    driver_opts:
      type: cifs
      o: username=xxx,password=xxx,uid=1000,gid=1000
      device: //192.168.100.39/data/transcode

services:
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node
    container_name: tdarr-node
    restart: unless-stopped
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Sao_Paulo
      - serverIP=192.168.100.39
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - media:/media
      - transcode:/tmp
      - tdarr:/app/configs
      - tdarr:/app/server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
```
