### ISSUE TITLE
Docker Node not using Intel QSV

### ISSUE THREAD

**Issue by matthewprobasco** [HaveAGitGat/Tdarr#977]
**Describe the bug**
I have TDARR server and node running in docker alongside plex container. Plex is using intel QSV without issue to transcode. The TDARR node does not use it and instead is always doing CPU transcode. 

**To Reproduce**
Docker Compose: 
```
version: "3.3"
networks:
  tdarr_network:
    external: true

services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    networks:
      tdarr_network:
        ipv4_address: 172.21.0.10
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    volumes:
      - /media/DOCKER_LOCAL_PERSISTENT_DATA/tdarr/server:/app/server
      - /media/DOCKER_PERSISTENT_DATA/tdarr/configs:/app/configs
      - /media/DOCKER_PERSISTENT_DATA/tdarr/logs:/app/logs
      - /media/PLEX_DATA/data/media:/media
      - /media/PLEX_DATA/transcode/tdarr:/temp
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - stack.env
    environment:
      - UMASK_SET=002
      - serverIP=172.21.0.10 #0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - inContainer=true
      - ffmpegVersion=6
    devices:
      - /dev/dri:/dev/dri
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    networks:
      tdarr_network:
        ipv4_address: 172.21.0.11
    volumes:
      - /media/DOCKER_PERSISTENT_DATA/tdarr/configs:/app/configs
      - /media/DOCKER_PERSISTENT_DATA/tdarr/logs:/app/logs
      - /media/PLEX_DATA/data/media:/media
      - /media/PLEX_DATA/transcode/tdarr:/temp
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - stack.env
    environment:
      - UMASK_SET=002
      - nodeName=MyExternalNode
      - serverIP=172.21.0.10
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=6
    devices:
      - /dev/dri:/dev/dri
```
Using default Tdarr transcode steps:
Tdarr_Plugin_MC93_Migz1FFMPEG_CPU

Docker test returns without issue: 
```
docker run \
    --device=/dev/dri:/dev/dri \
    ghcr.io/haveagitgat/tdarr_node:latest \
    /bin/bash -e \
    -c 'ffmpeg \
            -hwaccel qsv -f lavfi -i color=c=black:s=256x256:d=1:r=30 \
            -c:v:0 hevc_qsv \
            -f null /dev/null'
```

FFMPEG Test returns without issue: 
<img width="1227" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/45771785/02e8812f-aca6-47dc-9e6c-0464fb4c6379">

However when it runs I see my CPU gets hosed and there is not activity in the igpu: 
<img width="1238" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/45771785/70831354-0917-4dfa-9311-24282b24f74a">

<img width="917" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/45771785/ab6236b6-719f-4128-af7b-e3b7ef9317d1">

**Expected behavior**
CPU Use should be minimal and Intel iGPU should be used for HW Accelerated Transcoding

**Screenshots**
<img width="1014" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/45771785/443d2b66-7899-494f-ae7b-3426edd728d6">

<img width="946" alt="image" src="https://github.com/HaveAGitGat/Tdarr/assets/45771785/d1b2e6d7-b9a7-4394-bd54-24fc00b2f9d4">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
```
root@cb07d86c3dec:/# cat /app/configs/Tdarr_Server_Config.json 
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "172.21.0.10",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": ""
}root@cb07d86c3dec:/# 
```
```
root@a6a207e493c9:/# cat /app/configs/Tdarr_Node_Config.json 
{
  "nodeName": "MyExternalNode",
  "serverIP": "172.21.0.10",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": ""
}root@a6a207e493c9:/# 
```

- Job reports: https://docs.tdarr.io/docs/other/job-reports

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]

 - OS: Ubuntu
 - Browser: Safari
